### ISSUE TITLE
[15] 	product_supplierinfo_for_customer don´t install

### ISSUE THREAD

**Issue by SIC-brunorocha** [OCA/product-attribute#1224]
Disclaimer : First ever post in Issues section

## Module
product_supplierinfo_for_customer

## Describe the bug
Fail to install

## To Reproduce
V15

1.Download
2.Install

**Expected behavior**
To be instalable

**Additional context**
 File "/home/odoo/src/user/product_supplierinfo_for_customer/models/product_supplierinfo.py", line 6, in <module>
    class ProductSupplierInfo(models.Model):
  File "/home/odoo/src/user/product_supplierinfo_for_customer/models/product_supplierinfo.py", line 24, in ProductSupplierInfo
    @api.multi
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: module 'odoo.api' has no attribute 'multi'

**Comment by pedrobaeza** [comment]
You haven't downloaded the module for the correct version.
