### ISSUE TITLE
fixed pricelist is simply not working on 8.0

### ISSUE THREAD

**Issue by NL66278** [OCA/product-attribute#126]
The following errors occurs when selecting fixed price:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoivlprd80/odoo/parts/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoivlprd80/odoo/parts/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoivlprd80/odoo/parts/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoivlprd80/odoo/parts/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoivlprd80/odoo/parts/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/odoivlprd80/odoo/parts/odoo/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/home/odoivlprd80/odoo/parts/odoo/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoivlprd80/odoo/parts/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoivlprd80/odoo/parts/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/odoivlprd80/odoo/parts/odoo/openerp/api.py", line 256, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoivlprd80/odoo/parts/odoo/openerp/api.py", line 387, in old_api
    result = method(recs, _args, *_kwargs)
  File "/home/odoivlprd80/odoo/parts/odoo/openerp/models.py", line 5957, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/odoivlprd80/odoo/parts/odoo/openerp/models.py", line 5815, in _onchange_eval
    method_res = method(self)
  File "/home/odoivlprd80/odoo/parts/product_attribute/product_pricelist_fixed_price/model/product_pricelist_item.py", line 48, in change_base_ext
    self.base = base[0]
  File "/home/odoivlprd80/odoo/parts/odoo/openerp/fields.py", line 835, in __set__
    value = self.convert_to_cache(value, record)
  File "/home/odoivlprd80/odoo/parts/odoo/openerp/fields.py", line 1404, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for product.pricelist.item.base: product.price.type(1,)

**Comment by aristobulo-eezee** [comment]
Are you using migrated data?

I had the same issue with a migration, I solved it by doing:

```
UPDATE product_pricelist_item SET base = (
SELECT res_id FROM ir_model_data WHERE model = 'product.price.type' AND name='list_price') 
WHERE base = -3;
```

I think it should be included in the pre_init_hook.

Hope it helps.

**Comment by NL66278** [comment]
That was one of the problems. I am preparing a branch to put back all the missing pieces that were present in the 7.0 branch: https://github.com/nl66278/product-attribute/tree/8.0-fixed-pricelist-fixed  
I will add some unit tests before making a pull request.

**Comment by pedrobaeza** [comment]
This should be fixed... although there's another problem
