### ISSUE TITLE
[8.0][Installing] ImportError: cannot import name models

### ISSUE THREAD

**Issue by Segebre** [OCA/product-attribute#147]
-mkdir /opt/odoo/custom/addons
-cd "/opt/odoo/custom/addons"
-git clone https://github.com/OCA/product_attribute --branch 8.0 [Error 1]

[Error 1]
remote: Repository not found.
fatal: repository 'https://github.com/OCA/product_attribute/' not found
[Error 1]

-git clone https://github.com/OCA/product-attribute --branch 8.0 [Error 1 Fixed]
-sudo nano /etc/odoo/openerp-server.conf
(add) /opt/odoo/custom/addons/product-attribute
(save and exit with "ctrl + x", press "y", and "Enter")
-reboot

Go to your odoo, login, configuration, update module list(if this option is not visible, turn on technical features)

[Error 2]

Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 576, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in checked_call
    return self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 805, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 405, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 439, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 443, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/wizard/base_module_update.py", line 15, in update_module
    self.updated, self.added = self.env['ir.module.module'].update_list()
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 651, in update_list
    handler.load_addons()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1312, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/usr/lib/python2.7/dist-packages/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/custom/addons/product-attribute/product_multi_image/**init**.py", line 7, in <module>
    from . import models
ImportError: cannot import name models

[Error 2]

**Comment by pedrobaeza** [comment]
This is working properly, so you should check last updates and try again.
