### ISSUE TITLE
[16.0] product_pricelist_direct_print: 'product.pricelist.print' object has no attribute 'show_attribute_values'

### ISSUE THREAD

**Issue by manuelcalerosolis** [OCA/product-attribute#1593]
In the last revision, an error occurs when trying to enter the printing of rates.

## Module
product_pricelist_print

## To Reproduce
**Affected versions**:
16.0

1. Just run this module

**Error**
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1636, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1663, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1867, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/auto/addons/website/models/ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 700, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 6578, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/custom/src/odoo/odoo/models.py", line 6289, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo/auto/addons/product_pricelist_direct_print/wizards/product_pricelist_print.py", line 110, in _onchange_show_variants
    self.show_attribute_values = False
AttributeError: 'product.pricelist.print' object has no attribute 'show_attribute_values'

The above server error caused the following client error:
null

**Comment by legalsylvain** [comment]
hi @suker. could you take a look on this one ? I guess this problem has been introduced by  https://github.com/OCA/product-attribute/pull/1577

Thanks.
