### ISSUE TITLE
[8.0][product_gtin] Some UPC-A barcodes are not verified correctly

### ISSUE THREAD

**Issue by azeemism** [OCA/product-attribute#230]
Hi,

After installing product_gtin

![2017-02-08 12_45_58-local modules - erp](https://cloud.githubusercontent.com/assets/10731034/22756671/b7e67c12-edfc-11e6-9a69-c55fdd2bd9a3.png)

I noticed that some barcodes do not work. As an example I used the following UPC-A barcode `623543740440`

![2017-02-08 12_45_12-products - erp](https://cloud.githubusercontent.com/assets/10731034/22756833/50b570b0-edfd-11e6-90d0-3af0f9c57665.png)

However the barcode is correct.

![2017-02-08 12_50_37-check digit calculator _ gs1](https://cloud.githubusercontent.com/assets/10731034/22756858/73347ffa-edfd-11e6-8b60-131a19601b0b.png)

Changing the UPC-A barcode to an EAN13 format by adding a zero before the barcode work, but then I am no longer using a UPC-A barcode.

![2017-02-08 12_54_24-products - erp](https://cloud.githubusercontent.com/assets/10731034/22756966/e1c1fefc-edfd-11e6-9b97-d8908bf374e2.png)

Looks to me like a bug.

Thanks for all you do.

**Comment by azeemism** [comment]
The following error appears in the log file:

```
2017-02-08 23:05:49,217 45975 ERROR erp-example-com openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/oca80/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/oca80/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/oca80/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/oca80/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/oca80/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/oca80/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/oca80/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons-private/webkul/odoo_magento_connect/models/core_overrides.py", line 205, in write
    return super(product_template, self).write(cr, uid, ids, vals, context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/oca80/addons-oca/product-attribute/pricelist_per_product/product.py", line 51, in write
    return super(ProductTemplate, self).write(vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/oca80/addons/stock/product.py", line 502, in write
    return super(product_template, self).write(cr, uid, ids, vals, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons/product/product.py", line 772, in write
    res = super(product_template, self).write(cr, uid, ids, vals, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/oca80/addons-oca/connector/connector/producer.py", line 64, in write
    result = write_original(self, vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 3814, in write
    self._write(old_vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 3964, in _write
    result += self._columns[field].set(cr, self, id, field, vals[field], user, context=rel_context) or []
  File "/opt/odoo/oca80/openerp/osv/fields.py", line 1485, in set
    self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
  File "/opt/odoo/oca80/openerp/osv/fields.py", line 1524, in _related_write
    instance.write({self.arg[-1]: values})
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/oca80/addons-private/webkul/odoo_magento_connect/models/core_overrides.py", line 376, in write
    return super(product_product, self).write(cr, uid, ids, vals, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/oca80/addons-oca/connector/connector/producer.py", line 64, in write
    result = write_original(self, vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 3814, in write
    self._write(old_vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 3993, in _write
    recs._validate_fields(vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 1275, in _validate_fields
    raise ValidationError('\n'.join(errors))
ValidationError: ('ValidateError', u'Field(s) `ean13` failed against a constraint: Error: Invalid EAN/GTIN code')
```

**Comment by azeemism** [comment]
Here is another UPC-A code that does not work even though the check bit is correct:
`623543742680`

**Comment by azeemism** [comment]
Here is another UPC-A code that does not work even though the check digit is correct:
623543741560

Verified Check Digit at,
http://www.gs1.org/check-digit-calculator
62354374156
