### ISSUE TITLE
[8.0][product_gtin] Question: Any one have compatability issues with product_multi_ean

### ISSUE THREAD

**Issue by azeemism** [OCA/product-attribute#231]
I am curious whether the modules below can be used with `product_gtin` 
```
product_multi_ean
stock_inventory_barcode
```
https://github.com/OCA/stock-logistics-barcode/tree/8.0/product_multi_ean
https://github.com/OCA/stock-logistics-barcode/tree/8.0/stock_inventory_barcode
https://github.com/OCA/stock-logistics-barcode/tree/8.0

Thanks for your input.

**Comment by azeemism** [comment]
If both of the following are installed

```
product_multi_ean
product_gtin
```
I cannot enter a UPC-A Code in the product's "EAN13 Barcode" field. Appears that there is a compatibility issue. If this is something that is possible solve, that would be appreciated.

Thanks for all you do.

**Comment by azeemism** [comment]
Here is the log output:
```
2017-02-08 21:35:24,698 45974 ERROR erp-example-com openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/oca80/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/oca80/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/oca80/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/oca80/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/oca80/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/oca80/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/oca80/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons-private/webkul/odoo_magento_connect/models/core_overrides.py", line 205, in write
    return super(product_template, self).write(cr, uid, ids, vals, context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/oca80/addons-oca/product-attribute/pricelist_per_product/product.py", line 51, in write
     return super(ProductTemplate, self).write(vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/oca80/addons/stock/product.py", line 502, in write
    return super(product_template, self).write(cr, uid, ids, vals, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons/product/product.py", line 772, in write
    res = super(product_template, self).write(cr, uid, ids, vals, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/oca80/addons-oca/connector/connector/producer.py", line 64, in write
    result = write_original(self, vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 3814, in write
    self._write(old_vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 3964, in _write
    result += self._columns[field].set(cr, self, id, field, vals[field], user, context=rel_context) or []
  File "/opt/odoo/oca80/openerp/osv/fields.py", line 1485, in set
    self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
  File "/opt/odoo/oca80/openerp/osv/fields.py", line 1524, in _related_write
    instance.write({self.arg[-1]: values})
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
   File "/opt/odoo/oca80/addons-private/webkul/odoo_magento_connect/models/core_overrides.py", line 376, in write
    return super(product_product, self).write(cr, uid, ids, vals, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/oca80/addons-oca/connector/connector/producer.py", line 64, in write
    result = write_original(self, vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 3814, in write
    self._write(old_vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 3993, in _write
    recs._validate_fields(vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 1275, in _validate_fields
    raise ValidationError('\n'.join(errors))
ValidationError: ('ValidateError', u'Field(s) `ean13` failed against a constraint: You provided an invalid "EAN13 Barcode" reference. You may use the "Internal Reference" field instead.')
```

```
2017-02-08 22:22:33,701 45974 ERROR erp-example-com openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/oca80/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/oca80/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/oca80/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/oca80/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/oca80/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/oca80/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/oca80/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons-private/webkul/odoo_magento_connect/models/core_overrides.py", line 205, in write
    return super(product_template, self).write(cr, uid, ids, vals, context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/oca80/addons-oca/product-attribute/pricelist_per_product/product.py", line 51, in write
    return super(ProductTemplate, self).write(vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/oca80/addons/stock/product.py", line 502, in write
    return super(product_template, self).write(cr, uid, ids, vals, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons/product/product.py", line 772, in write
    res = super(product_template, self).write(cr, uid, ids, vals, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/oca80/addons-oca/connector/connector/producer.py", line 64, in write
    result = write_original(self, vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 3814, in write
    self._write(old_vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 3964, in _write
    result += self._columns[field].set(cr, self, id, field, vals[field], user, context=rel_context) or []
  File "/opt/odoo/oca80/openerp/osv/fields.py", line 1485, in set
    self._fnct_inv(obj, cr, user, id, name, value, self._fnct_inv_arg, context)
  File "/opt/odoo/oca80/openerp/osv/fields.py", line 1524, in _related_write
    instance.write({self.arg[-1]: values})
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/oca80/addons-private/webkul/odoo_magento_connect/models/core_overrides.py", line 376, in write
    return super(product_product, self).write(cr, uid, ids, vals, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons/mail/mail_thread.py", line 432, in write
    result = super(mail_thread, self).write(cr, uid, ids, values, context=context)
  File "/opt/odoo/oca80/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/oca80/addons-oca/connector/connector/producer.py", line 64, in write
    result = write_original(self, vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 3825, in write
    self._fields[key].determine_inverse(self)
  File "/opt/odoo/oca80/openerp/fields.py", line 953, in determine_inverse
    self.inverse(records)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons-oca/stock-logistics-barcode/product_multi_ean/models/product_product.py", line 64, in _inverse_ean13
    product.ean13_ids[:1].write({'name': product.ean13})
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/addons-oca/connector/connector/producer.py", line 64, in write
    result = write_original(self, vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 3814, in write
    self._write(old_vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 3993, in _write
    recs._validate_fields(vals)
  File "/opt/odoo/oca80/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/oca80/openerp/models.py", line 1285, in _validate_fields
    raise ValidationError("Error while validating constraint\n\n%s" % tools.ustr(e))
ValidationError: ('ValidateError', u'Error while validating constraint\n\nYou provided an invalid "EAN13 Barcode" reference. You may use the "Internal Reference" field instead.')
```

If the compatibility issue can be fixed that would be great!

Thanks for all you do.
