### ISSUE TITLE
product_default_image in odoo v10 breaks funcionality

### ISSUE THREAD

**Issue by vinclar** [OCA/product-attribute#352]
If this module is installed, you can't create products from sales, stock movements, etc
```
It throws on the log this error
http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/bus/controllers/main.py", line 35, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable
```

After uninstalling the module, funcionality is restored.

**Comment by pedrobaeza** [comment]
This has nothing to do with the module. It's a deployment problem on your side with workers, proxy and so on.
