### ISSUE TITLE
[V12]Product Brand Manager. Odoo Server Error at runbot after click 'sales'

### ISSUE THREAD

**Issue by GlenGuan** [OCA/product-attribute#426]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/models.py", line 1376, in load_views
    for [v_id, v_type] in views
  File "/.repo_requirements/odoo/odoo/models.py", line 1376, in <dictcomp>
    for [v_id, v_type] in views
  File "/home/odoo/OCB-12.0/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/.repo_requirements/odoo/odoo/models.py", line 1462, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 1092, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/.repo_requirements/odoo/odoo/addons/base/models/ir_ui_view.py", line 545, in raise_view_error
    raise ValueError(message)
ValueError: Field `sale_order_template_id` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]

**Comment by pedrobaeza** [comment]
This is not related to the module, but with Odoo. Please update your Odoo code to latest version.

**Comment by GlenGuan** [comment]
The error message shows on runbot.odoo-community.org, is it the latest version? And also, I cannot install it on a fresh installation of Odoo12 with sales module together.

**Comment by pedrobaeza** [comment]
The fix has been published in Odoo recently (as said, it's not something of `product_brand`, but Odoo itself. If you are using OCB, you have to wait until tomorrow to have the code updated.

**Comment by GlenGuan** [comment]
Still didn't work after reinstalling the Odoo 12 on Ubuntu 18.04 from Github or Nightly yesterday. Any relating link can be learned more? Thanks.
