### ISSUE TITLE
error while opening Pos session

### ISSUE THREAD

**Issue by mahmoudmk1** [OCA/product-attribute#556]
module: product_cost_security
version: 12.0

**Steps to reproduce**
- Dear Sir, I tested this module on my database and your demo server also, but I got this message every time I tried to open **PoS** session. only when I restrict user from cost feature? 

 Traceback (most recent call last): File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception return super(JsonRequest, self)._handle_exception(exception) File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception raise pycompat.reraise(type(exception), exception, sys.exc_info()[2]) File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise raise value File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch result = self._call_function(**self.params) File "/.repo_requirements/odoo/odoo/http.py", line 346, in _call_function return checked_call(self.db, *args, **kwargs) File "/.repo_requirements/odoo/odoo/service/model.py", line 97, in wrapper return f(dbname, *args, **kwargs) File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call result = self.endpoint(*a, **kw) File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__ return self.method(*args, **kw) File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap response = f(*args, **kw) File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 962, in call_kw return self._call_kw(model, method, args, kwargs) File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 954, in _call_kw return call_kw(request.env[model], method, args, kwargs) File "/.repo_requirements/odoo/odoo/api.py", line 755, in call_kw return _call_kw_model(method, model, args, kwargs) File "/.repo_requirements/odoo/odoo/api.py", line 728, in _call_kw_model result = method(recs, *args, **kwargs) File "/.repo_requirements/odoo/odoo/models.py", line 4595, in search_read result = records.read(fields) File "/.repo_requirements/odoo/odoo/models.py", line 2763, in read fields = self.check_field_access_rights('read', fields) File "/.repo_requirements/odoo/odoo/models.py", line 2743, in check_field_access_rights + ' - ({} {}, {} {})'.format(_('User:'), self._uid, _('Fields:'), ', '.join(invalid_fields)) odoo.exceptions.AccessError: ('The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: Product, Operation: read) - (User: 2, Fields: standard_price)', None

**Comment by ghost** [comment]
hi
cause POS user must access standard_price field , and (product_cost_security) module restrict the access to standard_price to only "Access to product costs" group users.
so either :
- Assign the user to "access to product costs" group.
- Uninstall the module.

**Comment by droidosergioh** [comment]
Hello,

Is there any solution for this? I do not think it is necesary that a vendor needs to access to the cost price in the POS
Kindest Regards

**Comment by andres-pcg** [comment]
Hey @sergio-teruel 

I'm having same issue. Is there any workaround on this one? 

While this module has a very good purpose on increasing security, it's not considering POS escenarios. 

cc: @pedrobaeza

**Comment by pedrobaeza** [comment]
If you want to use this module with pos, you need to develop a glue module for taking this into account. There's no solution in the main module.

**Comment by andres-pcg** [comment]
@pedrobaeza Understood. That should be addressed on the readme of the module to rise awareness to users, shouldn't it?

**Comment by pedrobaeza** [comment]
I'm seeing that https://github.com/OCA/product-attribute/tree/14.0/pos_product_cost_security exists.

**Comment by andres-pcg** [comment]
Thank you @pedrobaeza . We are going to do our best to back-port it. 

Regards,
